apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base

replicas:
  - name: hello
    count: 1

patches:
  - target:
      kind: Ingress
      name: hello
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: hello.home.arpa

labels:
  - pairs:
      env: home
      managed-by: argocd
    includeSelectors: false
    includeTemplates: true
